Screen:

	BoxLayout:
		size: 1,1
		
		MDFloatLayout:
			MDTextField:
				id: text1
				text: "1"
				pos_hint: {"center_x": .5, "center_y": .8}

			MDTextField:
				id: text2
				text: "1"
				pos_hint: {"center_x": .5, "center_y": .65}
					
			MDTextField:
				id: text3
				text: "1"
				pos_hint: {"center_x": .5, "center_y": .5}


			MDFlatButton:
				text: "Prueba"
				pos_hint: {"center_x": .5, "center_y": .35}
				size: .2, .2
				on_release: app.mod()
